### ISSUE TITLE
Fuji v2 todo list

### ISSUE THREAD

**Issue by dsrkafuu** [amzrk2/hugo-theme-fuji#21]
- [x] Base template
- [x] Base style
- [x] Dark mode
- [x] Comment area dark mode
- [x] SEO
- [x] Player
- [x] Syntax highlight with prism.js & autoloader
- [x] Syntax highlight dark mode
- [x] Replace "fat" Font Awesome
- [x] ToC fix
- [x] `exampleSite`
- [x] `README.md`

Preview: https://blog.amzrk2.cc/ (zh-Hans contents)
